#!/usr/bin/env python3
"""
Generate server/internal/masterdata/entities.go from schemas.json.

Emits one Go struct per entry in schemas.json so any table referenced from
Go code via `utils.ReadTable[EntityX](...)` is always available without
needing to teach this script which tables are "used". Each struct has all
fields in positional order with a `msgpack:",array"` sentinel so the
vmihailenco/msgpack decoder reads from positional arrays.

Usage:
  python scripts/gen_entities.py
"""

import json
import os
import re
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SCHEMAS_PATH = os.path.join(SCRIPT_DIR, "schemas.json")
# Base root (stands alone as `lunar-base/` or lives integrated as `<lunar-tear>/panel/`).
BASE_ROOT = os.path.dirname(SCRIPT_DIR)


def _resolve_server_dir() -> str:
    """Find the game server's server/ next to this base checkout.

    Integrated layout: <lunar-server>/panel/scripts -> <lunar-server>/server.
    Standalone layout: <parent>/lunar-base/scripts -> <parent>/lunar-server/server
    (or the legacy <parent>/lunar-tear/server).
    """
    integrated = os.path.join(BASE_ROOT, "..", "server")
    if os.path.isfile(os.path.join(integrated, "go.mod")):
        return os.path.normpath(integrated)
    sibling = os.path.join(BASE_ROOT, "..", "lunar-server", "server")
    if os.path.isfile(os.path.join(sibling, "go.mod")):
        return os.path.normpath(sibling)
    return os.path.join(BASE_ROOT, "..", "lunar-tear", "server")


MASTERDATA_DIR = os.path.join(_resolve_server_dir(), "internal", "masterdata")
OUTPUT_PATH = os.path.join(MASTERDATA_DIR, "entities.go")

TYPE_MAP = {
    "int": "int32",
    "long": "int64",
    "string": "string",
    "bool": "bool",
    "float": "float32",
    "double": "float64",
}


def go_type(schema_type: str) -> str:
    if schema_type in TYPE_MAP:
        return TYPE_MAP[schema_type]
    # Enum types and anything else -> int32
    return "int32"


def main():
    with open(SCHEMAS_PATH) as f:
        schemas = json.load(f)

    print(f"schemas.json: {len(schemas)} tables")

    lines = [
        "// Code generated by scripts/gen_entities.py from schemas.json. DO NOT EDIT.",
        "",
        "package masterdata",
        "",
    ]

    for table_key in sorted(schemas.keys()):
        entry = schemas[table_key]
        class_name = entry["class"]
        columns = sorted(entry["columns"], key=lambda c: c[0])

        lines.append(f"// {class_name} is table key \"{table_key}\".")
        lines.append(f"type {class_name} struct {{")
        lines.append(f'\t_ struct{{}} `msgpack:",array"`')
        for idx, typ, name in columns:
            gt = go_type(typ)
            lines.append(f"\t{name} {gt}")
        lines.append("}")
        lines.append("")

    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(lines))

    try:
        subprocess.run(["gofmt", "-w", OUTPUT_PATH], check=True)
    except (FileNotFoundError, subprocess.CalledProcessError) as exc:
        print(f"warning: gofmt step skipped: {exc}", file=sys.stderr)

    print(f"Generated {len(schemas)} structs -> {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
